### ISSUE TITLE
[MC-Version] Bug short description

### ISSUE THREAD

**Issue by ishmael10** [MC-U-Team/Enhanced-Anvil#3]
**Describe the bug**

**To Reproduce**
2. Do this '....'

**Expected behavior**

**Screenshots**

**Versions**
- Mod version: xxx
- Minecraft version: xxx
- Forge version: xxx
- UTeamCore version: xxx

**Log (if crash occures)**
Link to crash log

**Comment by HyCraftHD** [comment]
?
