### ISSUE TITLE
1.16.5] doesnt load it

### ISSUE THREAD

**Issue by ShappyIsHappy** [MC-U-Team/Enhanced-Anvil#7]
it doesnt whit my forge 

so can you do like video how u install it or something would mean alot <3
         
   -photo of the screen in minecraft-                                                                                                                                   
  (https://user-images.githubusercontent.com/83832750/117482276-cf0d0d80-af6c-11eb-8a5a-b4b92d619d76.PNG)
  
bye

**Comment by HyCraftHD** [comment]
Use at least 36.1.12 forge version.
You can just download the latest one here: 
https://files.minecraftforge.net/net/minecraftforge/forge/index_1.16.5.html
![image](https://user-images.githubusercontent.com/7681220/117483406-f6141100-af65-11eb-83c9-0fbeaa683d60.png)
